export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
// export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
// export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"